export interface ProductsAll{
    id:number, 
    name:string,
    category: string,
    description: string,
    price: number,
    title: string,
    hostUrl: string,
    size?: string,
    color?: string
}

export const productsData: ProductsAll[] = [
    {
        id: 1,
        name: 'Oversized Hoodie',
        category: 'Unisex',
        description: 'An oversized hoodie with a soft, cozy interior. Perfect for layering or lounging.',
        price: 59.99,
        title: 'Oversized Hoodie',
        hostUrl: '/images/oversized-hoodie.jpg',
        size: 'M',
        color: 'blue'
      },
      {
        id: 2,
        name: 'Cargo Pants',
        category: 'Men',
        description: 'Durable cargo pants with multiple pockets for a street-ready look.',
        price: 74.99,
        title: 'Cargo Pants',
        hostUrl: '/images/cargo-pants.jpg',
        size: 'S',
        color: 'blue'
      },
      {
        id: 3,
        name: 'Graphic Print T-Shirt',
        category: 'Women',
        description: 'A bold graphic t-shirt with unique street art designs.',
        price: 34.99,
        title: 'Print T-Shirt',
        hostUrl: '/images/graphic-print-tee.jpg',
        size: 'XL',
        color: 'orange'
      },
      {
        id: 4,
        name: 'Beanie Hat',
        category: 'Unisex',
        description: 'A soft beanie hat to keep you warm while looking cool.',
        price: 19.99,
        title: 'Beanie Hat',
        hostUrl: '/images/beanie-hat.jpg',
        size: 'M',
        color: 'green'
      },
      {
        id: 5,
        name: 'Drop Shoulder Sweatshirt',
        category: 'Men',
        description: 'Comfortable drop shoulder sweatshirt with a relaxed fit.',
        price: 54.99,
        title: 'Drop Sweatshirt',
        hostUrl: '/images/drop-shoulder-sweatshirt.jpg',
        size: 'M',
        color: 'red'
      },
      {
        id: 6,
        name: 'Plaid Flannel Shirt',
        category: 'Women',
        description: 'A trendy plaid flannel shirt with a loose fit, perfect for layering.',
        price: 49.99,
        title: 'Plaid Flannel Shirt',
        hostUrl: '/images/plaid-flannel-shirt.jpg',
        size: 'S',
        color: 'red'
      },
      {
        id: 7,
        name: 'Bucket Hat',
        category: 'Unisex',
        description: 'A reversible bucket hat with street style edge.',
        price: 24.99,
        title: 'Bucket Hat',
        hostUrl: '/images/bucket-hat.jpg',
        size: 'XL',
        color: 'blue'
      },
      {
        id: 8,
        name: 'Streetwear Joggers',
        category: 'Men',
        description: 'Comfortable joggers with a relaxed fit and drawstring waist.',
        price: 64.99,
        title: 'Joggers',
        hostUrl: '/images/streetwear-joggers.jpg',
        size: 'L',
        color: 'blue',
      },
      {
        id: 9,
        name: 'Oversized Bomber Jacket',
        category: 'Women',
        description: 'An oversized bomber jacket for a casual and stylish streetwear look.',
        price: 99.99,
        title: 'Bomber Jacket',
        hostUrl: '/images/oversized-bomber-jacket.jpg',
        size: 'S',
        color: 'red'
      },
      {
        id: 10,
        name: 'Sneakers with Chunky Soles',
        category: 'Unisex',
        description: 'High-top sneakers with chunky soles for ultimate streetwear vibes.',
        price: 119.99,
        title: 'Chunky Sneakers',
        hostUrl: '/images/chunky-sneakers.jpg',
        size: 'S',
        color: 'blue'
      },
      {
        id: 11,
        name: 'Techwear Vest',
        category: 'Men',
        description: 'A functional techwear vest with multiple pockets and a minimalist design.',
        price: 79.99,
        title: 'Techwear Vest',
        hostUrl: '/images/techwear-vest.jpg',
        size: 'L',
        color: 'green'
      },
      {
        id: 12,
        name: 'Tie-Dye Hoodie',
        category: 'Women,Man',
        description: 'A colorful tie-dye hoodie that makes a statement in any streetwear wardrobe.',
        price: 69.99,
        title: 'Tie-Dye Hoodie',
        hostUrl: '/images/tie-dye-hoodie.jpg',
        size: 'M',
        color: 'green'
      },
      {
        id: 13,
        name: 'Ripped Skinny Jeans',
        category: 'Unisex',
        description: 'Ripped skinny jeans for a grunge-inspired street style.',
        price: 59.99,
        title: 'Ripped Jeans',
        hostUrl: '/images/ripped-skinny-jeans.jpg',
        size: 'XL',
        color: 'orange'
      },
      {
        id: 14,
        name: 'Streetwear Shorts',
        category: 'Men',
        description: 'Comfortable and breathable streetwear shorts with a relaxed fit.',
        price: 44.99,
        title: 'Overisized Shorts',
        hostUrl: '/images/streetwear-shorts.jpg',
        size: 'M',
        color: 'blue'
      },
      {
        id: 15,
        name: 'Utility Jacket',
        category: 'Women',
        description: 'A practical utility jacket with plenty of pockets and a sleek design.',
        price: 109.99,
        title: 'Utility Jacket',
        hostUrl: '/images/utility-jacket.jpg',
        size: 'S',
        color: 'red'
      },
      {
        id: 16,
        name: 'Streetwear Baseball Jersey',
        category: 'Unisex',
        description: 'A baseball jersey with streetwear influences, perfect for casual outings.',
        price: 79.99,
        title: 'Baseball Jersey',
        hostUrl: '/images/baseball-jersey.jpg',
        size: 'S',
        color: 'green'
      },
      {
        id: 17,
        name: 'Camouflage Cargo Pants',
        category: 'Men',
        description: 'Classic camouflage cargo pants with a relaxed fit and multiple pockets.',
        price: 69.99,
        title: 'Cargo Pants',
        hostUrl: '/images/camouflage-cargo-pants.jpg',
        size: 'M',
        color: 'blue'
      },
      {
        id: 18,
        name: 'Patchwork Denim Jacket',
        category: 'Women',
        description: 'A patchwork denim jacket that stands out in any crowd.',
        price: 119.99,
        title: 'Denim Jacket',
        hostUrl: '/images/patchwork-denim-jacket.jpg',
        size: 'XL',
        color: 'orange'
      },
      {
        id: 19,
        name: 'Streetwear Track Pants',
        category: 'Unisex',
        description: 'Lightweight track pants with side stripes for a sporty streetwear look.',
        price: 59.99,
        title: 'Track Pants',
        hostUrl: '/images/track-pants.jpg',
        size: 'XL',
        color: 'green'
      },
      {
        id: 20,
        name: 'Street Graphic Long Sleeve Tee',
        category: 'Men',
        description: 'A long sleeve tee with bold street graphics for a modern, edgy look.',
        price: 39.99,
        title: 'Long Sleeve Tee',
        hostUrl: '/images/graphic-long-sleeve.jpg',
        size: 'M',
        color: 'green'
      },{
        id: 21,
        name: 'Mini Graphic Hoodie',
        category: 'Kids',
        description: 'A mini version of our popular graphic hoodie, perfect for stylish kids.',
        price: 39.99,
        title: 'Graphic Hoodie',
        hostUrl: '/images/mini-graphic-hoodie.jpg',
        size: 'L',
        color: 'red'
      },
      {
        id: 22,
        name: 'Kids Cargo Joggers',
        category: 'Kids',
        description: 'Comfortable cargo joggers for kids with an elastic waistband and multiple pockets.',
        price: 29.99,
        title: 'Cargo Joggers',
        hostUrl: '/images/kids-cargo-joggers.jpg',
        size: 'S',
        color: 'orange'
      },
      {
        id: 23,
        name: 'Tie-Dye T-Shirt',
        category: 'Kids',
        description: 'A vibrant tie-dye t-shirt that adds a pop of color to any kid’s wardrobe.',
        price: 19.99,
        title: 'Tie-Dye T-Shirt',
        hostUrl: '/images/kids-tie-dye-tee.jpg',
        size: 'XL',
        color: 'orange'
      },
      {
        id: 24,
        name: 'Snapback Cap',
        category: 'Kids',
        description: 'A cool snapback cap with adjustable sizing for a comfortable fit.',
        price: 14.99,
        title: 'Snapback Cap',
        hostUrl: '/images/kids-snapback-cap.jpg',
        size: 'M',
        color: 'blue'
      },
      {
        id: 25,
        name: 'Streetwear Puffer Jacket',
        category: 'Kids',
        description: 'A warm and stylish puffer jacket designed for both comfort and street cred.',
        price: 49.99,
        title: 'Puffer Jacket',
        hostUrl: '/images/kids-puffer-jacket.jpg',
        size: 'L',
        color: 'orange'
      },
      {
        id: 26,
        name: 'Fleece Lined Joggers',
        category: 'Kids',
        description: 'Soft fleece-lined joggers for extra warmth and comfort during cooler days.',
        price: 34.99,
        title: 'Fleece Joggers',
        hostUrl: '/images/kids-fleece-joggers.jpg',
        size: 'S',
        color: 'red'
      },
      {
        id: 27,
        name: 'Mini Bomber Jacket',
        category: 'Kids',
        description: 'A mini version of our popular bomber jacket, designed to keep kids warm and stylish.',
        price: 59.99,
        title: 'Bomber Jacket',
        hostUrl: '/images/kids-mini-bomber-jacket.jpg',
        size: 'S',
        color: 'orange'
      },
]